spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
logging:
  level:
    root: info
---
#spring:
#  profiles: 7900
server:
  port: 7900
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:7900/eureka/